const qs=s=>document.querySelector(s),chapters=[...document.querySelectorAll('.chapter')];
let current=0,xp=0;
const toast=t=>{const el=qs('#questToast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)};
function next(){if(!chapters.length)return;chapters[current]?.classList.remove('active');current=Math.min(current+1,chapters.length-1);chapters[current]?.classList.add('active');xp=Math.min(100,xp+25);const x=qs('#xp');if(x)x.textContent=xp;chapters[current]?.scrollIntoView({behavior:'smooth',block:'center'})}
qs('#startCampaign')?.addEventListener('click',()=>{const c=qs('#campaign');c?.classList.remove('hidden');c?.scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('.roll').forEach(b=>b.addEventListener('click',()=>{const n=1+Math.floor(Math.random()*20);b.nextElementSibling.textContent='🎲 Выпало '+n+'. '+(n>=12?'Успех! Сфинкс отступает.':'Неудача — но лисий жетон даёт переброс!');if(n>=12)setTimeout(next,900)}));
document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const r=qs('.choiceResult');if(!r)return;if(b.dataset.answer==='yes'){r.textContent='✨ Верно. d20 решает судьбу!';setTimeout(next,800)}else r.textContent='Почти. Вспомни главный кубик D&D.'}));
qs('#dndCheck')?.addEventListener('click',()=>{const input=qs('#dndCode'),r=qs('#dndResult');if(!input||!r)return;if(input.value.trim()==='2041'){r.textContent='🔓 Замок щёлкнул. За дверью пахнет лесом и приключением.';setTimeout(next,900)}else r.textContent='Руны гаснут. Проверь числа ещё раз.'});
qs('.trueEnding')?.addEventListener('click',()=>{const ending=qs('#ending');if(!ending)return;ending.innerHTML='<h3>🏆 ИСТИННАЯ КОНЦОВКА</h3><p>Янтарный Лис вручает тебе легендарный предмет: <b>«Кубик хороших воспоминаний»</b>. +20 к удаче, +100 к дружбе и бесконечный запас приключений.</p><div class="finishChoices"><a class="adventureBtn ghost" href="index.html">← Вернуться на праздник</a><a class="adventureBtn primary" href="finale.html">Открыть финальный подарок 💜 →</a></div>';localStorage.setItem('fox-campaign-complete','yes');toast('Кампания пройдена! 🦊🎲')});
document.querySelectorAll('.finalChoices button:not(.trueEnding)').forEach(b=>b.addEventListener('click',()=>{const e=qs('#ending');if(e)e.textContent='Лис улыбается: «Хороший вариант… но есть ответ теплее»'}));
const hints=['В первой главе нужен бросок 12 или выше. Можно бросать снова.','На мосту подумай о самом известном кубике D&D.','Код крепости: d20 максимум + 4 буквы в слове ЛИСА + один шпиль.','Финал не про цифры. Лучшие кампании запоминаются людьми и историей.'];let hi=0;
qs('#questHints')?.addEventListener('click',()=>{const t=qs('#questHintText'),m=qs('#questHintModal');if(t)t.textContent=hints[Math.min(hi++,hints.length-1)];m?.classList.add('show')});
qs('#closeQuestHint')?.addEventListener('click',()=>qs('#questHintModal')?.classList.remove('show'));