const body=document.body,buttons=document.querySelectorAll('[data-theme]');const saved=localStorage.getItem('birthday-theme');if(saved){body.dataset.theme=saved;buttons.forEach(b=>b.classList.toggle('active',b.dataset.theme===saved))}buttons.forEach(b=>b.onclick=()=>{body.dataset.theme=b.dataset.theme;localStorage.setItem('birthday-theme',b.dataset.theme);buttons.forEach(x=>x.classList.toggle('active',x===b))});
window.addEventListener('load',()=>setTimeout(()=>document.querySelector('#preloader').classList.add('hide'),650));
const gift=document.querySelector('#gift');document.querySelector('#openGift').onclick=()=>gift.classList.add('show');document.querySelector('#closeGift').onclick=()=>gift.classList.remove('show');gift.onclick=e=>{if(e.target===gift)gift.classList.remove('show')};
let pets=0;const toast=document.querySelector('#toast');document.querySelector('#petCat').onclick=()=>{pets++;document.querySelector('#pets').textContent=pets;toast.textContent=pets<10?'🐾 Кошечка довольна!':'😼 Ладно, ты принята в кошачью элиту.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1300);burst(innerWidth/2,innerHeight*.7,18)};
const canvas=document.querySelector('#fx'),ctx=canvas.getContext('2d');let bits=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);function burst(x,y,n=80){let icons=['💜','✨','🌸','🎀','⭐','🐾'];for(let i=0;i<n;i++)bits.push({x,y,vx:(Math.random()-.5)*12,vy:-Math.random()*10-3,g:.18+Math.random()*.1,r:Math.random()*6-3,a:1,s:14+Math.random()*15,t:icons[Math.floor(Math.random()*icons.length)]})}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);bits=bits.filter(p=>p.a>0);bits.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.a-=.012;ctx.globalAlpha=Math.max(0,p.a);ctx.font=p.s+'px sans-serif';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillText(p.t,0,0);ctx.restore()});ctx.globalAlpha=1;requestAnimationFrame(draw)}draw();document.querySelector('#boom').onclick=e=>{const r=e.target.getBoundingClientRect();burst(r.left+r.width/2,r.top,120);e.target.textContent='Бонус получен! ✨'};

const secretBtn=document.querySelector('#secretMenuBtn'),secretPanel=document.querySelector('#secretPanel'),eggCount=document.querySelector('#eggCount'),eggList=document.querySelector('#eggList'),hintText=document.querySelector('#hintText');
const eggNames=['Лапка в углу','Звёздная пыль','Лисий хвост','Пять поглаживаний','Десять поглаживаний','Подарок открыт','Бонус забран','Лисёнок разбужен','Лисий код','Секретный заголовок','Тройной клик','Konami-лиса','Ночная сова','Манга-охотник','Все темы'];
let found=new Set(JSON.parse(localStorage.getItem('birthday-eggs')||'[]'));
function saveEggs(){localStorage.setItem('birthday-eggs',JSON.stringify([...found]));renderEggs()}
function findEgg(name){if(found.has(name))return;found.add(name);saveEggs();toast.textContent='🥚 Пасхалка найдена: '+name;toast.classList.add('show');burst(innerWidth/2,innerHeight/2,35);setTimeout(()=>toast.classList.remove('show'),1800)}
function renderEggs(){eggCount.textContent=found.size;eggList.innerHTML=eggNames.map(n=>'<div class="eggItem '+(found.has(n)?'':'locked')+'">'+(found.has(n)?'✓ '+n:'???')+'</div>').join('')}
renderEggs();secretBtn.onclick=()=>secretPanel.classList.add('show');document.querySelector('#closeSecrets').onclick=()=>secretPanel.classList.remove('show');secretPanel.onclick=e=>{if(e.target===secretPanel)secretPanel.classList.remove('show')};
document.querySelectorAll('[data-egg]').forEach(e=>e.onclick=()=>findEgg(e.dataset.egg));
const hints=['Посмотри в самые края страницы.','Кошечку иногда нужно гладить не один раз.','Подарок скрывает больше одного секрета.','Попробуй нажать на лисёнка.','Классическая игровая комбинация клавиш тоже кое-что знает.','Переключи все четыре темы хотя бы по разу.','Заголовок страницы любит быстрые клики.','Загляни в раздел манги и нажми на громкое слово.'];
let hi=0;document.querySelector('#hintBtn').onclick=()=>{hintText.textContent=hints[hi++%hints.length]};
document.querySelector('#foxHero').onclick=()=>findEgg('Лисёнок разбужен');
document.querySelector('#checkCode').onclick=()=>{const v=document.querySelector('#questCode').value.trim(),out=document.querySelector('#questResult');if(v==='941'){out.textContent='🦊 Верно! Нора открыта. Секрет: «Ты — главный персонаж этой истории!»';findEgg('Лисий код')}else out.textContent='Хм… лисёнок качает головой. Попробуй ещё.'};
document.querySelector('#openGift').addEventListener('click',()=>findEgg('Подарок открыт'));document.querySelector('#boom').addEventListener('click',()=>findEgg('Бонус забран'));
document.querySelector('#petCat').addEventListener('click',()=>{if(pets>=5)findEgg('Пять поглаживаний');if(pets>=10)findEgg('Десять поглаживаний')});
let titleClicks=0;document.querySelector('h1').addEventListener('click',()=>{if(++titleClicks>=3)findEgg('Секретный заголовок')});
let clicks=0,timer;document.addEventListener('click',()=>{clicks++;clearTimeout(timer);timer=setTimeout(()=>clicks=0,500);if(clicks===3)findEgg('Тройной клик')});
document.querySelector('.sfx').addEventListener('click',()=>findEgg('Манга-охотник'));
let seq=[],kon=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];document.addEventListener('keydown',e=>{seq.push(e.key);seq=seq.slice(-10);if(seq.join('|')===kon.join('|'))findEgg('Konami-лиса')});
if(new Date().getHours()<5)findEgg('Ночная сова');
let usedThemes=new Set(JSON.parse(localStorage.getItem('used-themes')||'[]'));document.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>{usedThemes.add(b.dataset.theme);localStorage.setItem('used-themes',JSON.stringify([...usedThemes]));if(usedThemes.size>=4)findEgg('Все темы')}));
